server:
  port: 8080

database:
  dbhost: "localhost"
  dbport: "5432"
  dbname: "mydb"
  dbuser: "test"
  dbpassword: "1234567890"
  dbtimezone: "UTC"
  dbsslmode: "disable"

mqtt:
  broker: "mqtt.gridinstruments.com"
  port: 1883
  username: "mqttuser"
  clientId: "mqttclient"
  password: "mqttpassword"
  topic: "dev/#"


EXAMPLE_VAR: "variable from config.yml"
EXAMPLE_PATH: "path from config.yml"